[package]
name = "smt"
version = "0.1.0"
edition = "2021"
authors = ["Guangyu Zhu <guangyuz@gmail.com>"]

[dependencies]
halo2_proofs = { git = "https://github.com/zcash/halo2.git", tag = "halo2_gadgets-0.3.0" }
halo2_gadgets = { git = "https://github.com/zcash/halo2.git", tag = "halo2_gadgets-0.3.0" }
pasta_curves = "0.5"
ark-std = { version = "^0.3.0", default-features = false }
anyhow = "1.0.41"
ff = "0.13"
rand = "0.8"
rayon = "1"

